import pandas as pd
import sqlite3
import streamlit as st
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.data as pldata
from pathlib import Path

db_path = Path(__file__).parent.parent / "db" / "lesson.db"

# Task 1
st.title("Employee Performance Dashboard")

# Connect to database
with sqlite3.connect(db_path) as conn:
    query = """
    SELECT last_name, 
    SUM(price * quantity) AS revenue 
    FROM employees e 
    JOIN orders o ON e.employee_id = o.employee_id 
    JOIN line_items l ON o.order_id = l.order_id 
    JOIN products p ON l.product_id = p.product_id 
    GROUP BY e.employee_id;
    """
    # Load results into Dataframe
    employee_results = pd.read_sql(query, conn)

# Create bar chart
fig, ax = plt.subplots()
employee_results.plot(
    x="last_name", 
    y="revenue", 
    kind="bar", 
    color="green", 
    ax=ax
    )
ax.set_title("Revenue Generated by Employee")
ax.set_xlabel("Employee Last Name")
ax.set_ylabel("Revenue")
st.pyplot(fig)

# Task 2
st.title("Cumulative Revenue")
# Connect to database
with sqlite3.connect(db_path) as conn:
    query = """
    SELECT 
    orders.order_id,
    SUM(products.price * line_items.quantity) AS total_price
    FROM orders
    JOIN line_items ON orders.order_id = line_items.order_id
    JOIN products ON line_items.product_id = products.product_id
    GROUP BY orders.order_id
    ORDER BY orders.order_id;
    """
    df = pd.read_sql(query, conn)

# Create cumulative revenue column
df["cumulative"] = df["total_price"].cumsum()
fig2, ax2 = plt.subplots()
df.plot(
    x="order_id", 
    y="cumulative", 
    kind="line", 
    color="green", 
    ax=ax2
    )
ax2.set_title("Cumulative Revenue Over Time")
ax2.set_xlabel("Order ID")
ax2.set_ylabel("Cumulative Revenue")
st.pyplot(fig2)

# Task 3
st.title("Wind Data")
df = pldata.wind(return_type='pandas')

df["strength"] = df["strength"].str.replace(r"[^0-9.]", "", regex=True).astype(float)
st.dataframe(df.head(10))
fig3 = px.scatter(
    df, 
    x="strength",
    y="frequency", 
    color="direction", 
    title="Wind Strength vs Frequency",
    labels={
       "strength": "Wind Strength",
       "frequency": "Frequency",
       "direction": "Wind Direction"
    }
    )
st.plotly_chart(fig3)
